name:  Build and Deploy Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'

    - name: Build Docker image
      run: |
        docker build -t chatbot-app .

    - name: Save Docker image to file
      run: |
        docker save chatbot-app | gzip > chatbot-app.tar.gz

    - name: Copy Docker image to remote server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASS }}
        port: 22
        source: "chatbot-app.tar.gz"
        target: "/home/knu_in2/chatbot-app.tar.gz"

    - name: SSH and load Docker image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASS }}
        port: 22
        script: |
          docker load < /home/knu_in2/chatbot-app.tar.gz
          docker run -d -p 6677:6677 --name chatbot-app chatbot-app
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
